services:
  postgres:
    image: postgres:15-alpine
    container_name: iot_kpi_postgres
    environment:
      POSTGRES_DB: iot_kpi_db
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot_user -d iot_kpi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: iot_kpi_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iot_network

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: iot_kpi_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://iot_user:iot_password@postgres:5432/iot_kpi_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - iot_network

  data_collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: iot_kpi_collector
    environment:
      - DATABASE_URL=postgresql://iot_user:iot_password@postgres:5432/iot_kpi_db
      - REDIS_URL=redis://redis:6379
      - SAMASTH_API_URL=https://samasth.io/api
      - SAMASTH_TOKEN=${SAMASTH_TOKEN}
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./python_loader:/app/python_loader
      - ./prod_batch_uptime_results.csv:/app/prod_batch_uptime_results.csv
    networks:
      - iot_network

  redis:
    image: redis:7-alpine
    container_name: iot_kpi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.8.0
    container_name: iot_kpi_airflow_init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://iot_user:iot_password@postgres:5432/iot_kpi_db
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-secret-key
      - AIRFLOW__WEBSERVER__AUTHENTICATE=true
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.www.auth
      - AIRFLOW__CORE__AUTHENTICATE=true
      - SAMASTH_TOKEN=${SAMASTH_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/opt/airflow/project
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    user: "${AIRFLOW_UID:-50000}:0"
    command: airflow db migrate
    networks:
      - iot_network

  airflow-webserver:
    image: apache/airflow:2.8.0
    container_name: iot_kpi_airflow_webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://iot_user:iot_password@postgres:5432/iot_kpi_db
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-secret-key
      - AIRFLOW__WEBSERVER__AUTHENTICATE=true
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.www.auth
      - AIRFLOW__CORE__AUTHENTICATE=true
      - SAMASTH_TOKEN=${SAMASTH_TOKEN}
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - .:/opt/airflow/project
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    user: "${AIRFLOW_UID:-50000}:0"
    command: airflow webserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - iot_network

  airflow-scheduler:
    image: apache/airflow:2.8.0
    container_name: iot_kpi_airflow_scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://iot_user:iot_password@postgres:5432/iot_kpi_db
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=your-secret-key
      - SAMASTH_TOKEN=${SAMASTH_TOKEN}
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - .:/opt/airflow/project
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    user: "${AIRFLOW_UID:-50000}:0"
    command: airflow scheduler
    networks:
      - iot_network

  nginx:
    image: nginx:alpine
    container_name: iot_kpi_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - grafana
      - airflow-webserver
    networks:
      - iot_network

volumes:
  postgres_data:
  grafana_data:
  redis_data:

networks:
  iot_network:
    driver: bridge
