apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: 000000001
    access: proxy
    url: postgres:5432
    database: iot_kpi_db
    user: iot_user
    secureJsonData:
      password: iot_password
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      maxOpenConnsIdleTime: 14400
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
